const FIELD_LABELS: Record<string, string> = {
  eyebrow: 'Occhiello',
  title: 'Titolo',
  titleAccent: 'Accento titolo (corsivo)',
  subtitle: 'Sottotitolo',
  description: 'Descrizione',
  intro: 'Introduzione',
  label: 'Etichetta',
  href: 'Link (href)',
  ctaLabel: 'Testo CTA',
  ctaHref: 'Link CTA',
  linkLabel: 'Testo link',
  linkHref: 'Link',
  placeholder: 'Placeholder',
  messages: 'Messaggi',
  links: 'Link',
  items: 'Elementi',
  columns: 'Colonne menu',
  columnTitle: 'Titolo colonna',
  panel: 'Pannello mega-menu',
  promo: 'Promo',
  footerLine: 'Riga footer',
  chips: 'Chip',
  hints: 'Suggerimenti',
  bullets: 'Elenco puntato',
  cards: 'Card',
  code: 'Codice',
  hint: 'Suggerimento',
  imageUrl: 'URL immagine',
  videoUrl: 'URL video (opzionale)',
  coverImage: 'Copertina articolo',
  caption: 'Didascalia',
  alt: 'Testo alternativo (alt)',
  layout: 'Layout',
  paragraphs: 'Paragrafi',
  category: 'Categoria',
  meta: 'Meta',
  variant: 'Variante',
  kind: 'Tipo blocco',
  primaryLabel: 'CTA primaria',
  primaryHref: 'Link CTA primaria',
  secondaryLabel: 'CTA secondaria',
  secondaryHref: 'Link CTA secondaria',
  blocks: 'Blocchi',
  form: 'Form',
  heroBadges: 'Badge hero',
  legalNote: 'Nota legale',
  footerNote: 'Nota a piè pagina',
  notFoundCta: 'CTA pagina non trovata',
  utilityBar: 'Barra utilità',
  nav: 'Navigazione',
  trustBar: 'Barra fiducia',
  footer: 'Footer',
  social: 'Social',
  addressLines: 'Righe indirizzo',
  hoursLines: 'Righe orari',
  hero: 'Hero',
  search: 'Ricerca',
  sockets: 'Attacchi',
  paths: 'Percorsi',
  rooms: 'Ambienti',
  designShowcase: 'Vetrina design',
  technicalShowcase: 'Vetrina tecnica',
  brands: 'Brand',
  guides: 'Guide',
  b2b: 'B2B',
  leadGen: 'Lead generation',
  newsletter: 'Newsletter',
  worlds: 'Mondi catalogo',
  design: 'Design',
  technical: 'Tecnico',
  defaultQuery: 'Query predefinita',
  searchQuery: 'Query ricerca',
  productCount: 'N. prodotti',
  privacyNote: 'Nota privacy',
  quickReorder: 'Riordino rapido',
  features: 'Vantaggi',
  audiences: 'Target',
  registration: 'Registrazione',
  exampleLines: 'Righe esempio',
  footnote: 'Nota a piè',
  loginHint: 'Suggerimento login',
  formNote: 'Nota form',
  submitLabel: 'Testo invio',
  sectors: 'Settori',
  fields: 'Campi form',
  placeholders: 'Placeholder campi',
  companyName: 'Ragione sociale',
  vat: 'Partita IVA',
  sector: 'Settore',
  contactName: 'Referente',
  email: 'Email',
  phone: 'Telefono',
  message: 'Messaggio',
  primaryCta: 'CTA primaria',
  secondaryCta: 'CTA secondaria',
  benefits: 'Benefici',
  seo: 'SEO',
  noindex: 'No index',
  cta: 'Call to action',
  company: 'Azienda',
  rea: 'REA',
  address: 'Indirizzo',
  phoneHref: 'Link telefono',
  hours: 'Orari',
  whatsapp: 'WhatsApp',
  num: 'Numero',
}

const TEXTAREA_KEYS = new Set([
  'description',
  'intro',
  'subtitle',
  'privacyNote',
  'footerNote',
  'legalNote',
  'footnote',
  'formNote',
  'loginHint',
  'message',
])

const TECHNICAL_KEYS = new Set([
  'href',
  'ctaHref',
  'linkHref',
  'imageUrl',
  'videoUrl',
  'phoneHref',
  'whatsapp',
  'kind',
  'variant',
  'form',
  'layout',
  'id',
  'searchQuery',
  'defaultQuery',
  'noindex',
])

export function fieldLabel(key: string, index?: number) {
  const base = FIELD_LABELS[key] ?? key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase())
  if (index !== undefined) return `${base} ${index + 1}`
  return base
}

export function isTextareaField(key: string) {
  return TEXTAREA_KEYS.has(key)
}

export function isTechnicalField(key: string) {
  return TECHNICAL_KEYS.has(key)
}
