export type {
  OdooOrderSource,
  OdooStatusDTO,
  OdooSaleOrderLineDTO,
  OdooSaleDocumentDTO,
  OdooQuotationDetailDTO,
  OdooPricelistDTO,
  OdooPartnerPricelistDTO,
  OdooPricelistAssignmentDTO,
  OdooPaginatedDTO,
  OdooSaleDocumentListQuery,
  OdooPricelistListQuery,
  OdooSyncQueueItemDTO,
  OdooSyncQueueListDTO,
  OdooSyncOperationDTO,
} from '../../types/odoo.dto.js'
