-- Gruppo 3: campi fiscali utente B2B/professional
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isProfessional" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "vatNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "fiscalCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pec" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sdiCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "companyName" TEXT;
